ver: 1.0
env: local
datasource:
 url: jdbc:postgresql://localhost:5432/postgres
 user: postgres
 password: cm9vdEAxMjM0
 driverClassName: org.postgresql.Driver
 autoCommit: true
 idleTimeout: 10000
 minimumIdle: 1
 maximumPoolSize: 5
 maxLifeTime: 20000
 poolName: HikariCP-1
server:
 port: 4000
 servlet:
  context-path: /rest/api

logging:
 level:
  org.springframework: INFO
  com.restapi: DEBUG
 pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

