spring:
 ver: 1.0
 env: local
 datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  user: postgres
  password: root@1234
  driverClassName: org.postgresql.Driver   
 server:
  port: 8080
  contextPath: /rest/api

 logging:
  level:
   org.springframework: INFO
   com.restapi: DEBUG
  pattern:
   console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"